### PR TITLE
W8 Requirements

### PR DESCRIPTION
**Pull request by grantcm**
Enhanced with autocomplete for commands and updated documentation. Still need to add roles to the README

### CODE REVIEW

**Comment by eugenepeh** [comment]
Hey @grantcm @LauY99 @aali195 

Your team has forgotten to do some of the following in
https://nus-cs2103.github.io/website/admin/index.html#admin-project-v10 submission, please get it done soon.

**Comment by grantcm** [comment]
Hey @eugenepeh 

Are you referring to the requirements for Week 7 or Week 8? 

If Week 7 could you please specify what we haven't done yet?

This is my PR for Week 8, so it's going to be missing the update roles for myself and group members until we discuss.

**Comment by eugenepeh** [comment]
Hey @grantcm, you guys have missed out this

4. One member: create a PR from your team repo master branch to [nus-cs2103-AY1718S1/addressbook-level4] master branch. PR name: [W7.7][Team ID] Product Name e.g., [W7.7][T09-B2] Contact List Pro.  As you merge code to your team repo's master branch, this PR will auto-update to reflect how much your team's product has progressed.

Also, your organisation name has to follow the style 
CS2103AUG2017-T12-B4

**Comment by eugenepeh** [comment]
remember to enable issues too
image

**Comment by grantcm** [comment]
@eugenepeh should be finished now. Thanks for letting us know.

**Pull request merged**
